FROM debian:12

RUN apt-get update && apt-get install -y \
	wget \
	curl \
	vim \
	jq \
	lsb-release \
	openjdk-17-jre-headless \
	gnupg \
	software-properties-common \
	cmake \
	ninja-build \
	git \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

##################################
#####  THIRD-PARTY FOLDER  #######
##################################

# Copy all files
COPY third-party /project/third-party
COPY common.mk /project/common.mk

# Set the working directory for the third-party build
WORKDIR /project

##################################
#######	  DEBIAN & LLVM	  ########
##################################

# Dynamically add the official LLVM repository based on the Debian codename
RUN CODENAME=$(lsb_release -cs) \
	&& echo "deb http://apt.llvm.org/${CODENAME}/ llvm-toolchain-${CODENAME} main" > /etc/apt/sources.list.d/llvm.list \
	&& wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
	&& apt-get update

# Download and run the LLVM installation script
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh $(cat third-party/.versions/llvm-project | awk -F'[-.]' '{print $2}' | tr -s '\n') all

# Clean up
RUN rm llvm.sh

# Detect llvm version and create symlinks
RUN export LLVM_VERSION=$(ls /usr/bin | grep clang++ | tr -d 'clang++-'); \
	export LLVM_ROOT=$(llvm-config-$LLVM_VERSION --prefix); \
    for bin in $LLVM_ROOT/bin/*; do \
      bin=$(basename $bin); \
      if test -f /usr/bin/$bin-$LLVM_VERSION ; then \
        ln -sf /usr/bin/$bin-$LLVM_VERSION /usr/bin/$bin; \
      fi; \
    done; \
	rm -f /usr/bin/cc; \
	ln -sf /usr/bin/clang-$LLVM_VERSION /usr/bin/cc; \
	ln -sf /usr/bin/clang++-$LLVM_VERSION /usr/bin/c++;

# Add environment variables directly to Dockerfile
ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++

# Test LLVM
COPY test/cedc-system/test.sh .
COPY test/cedc-system/test.cpp .
RUN chmod +x test.sh && ./test.sh
RUN rm test.sh
RUN rm test.cpp

##################################
######      ANTLR            #####
##################################

# Fetch the latest ANTLR release tag from GitHub, download the jar file and create aliases
RUN ANTLR_VERSION=$(cat third-party/.versions/antlr) && \
    wget http://www.antlr.org/download/antlr-$ANTLR_VERSION-complete.jar -O /usr/local/lib/antlr-$ANTLR_VERSION-complete.jar && \
    echo '#! /bin/bash\n'\
'export CLASSPATH=".:/usr/local/lib/antlr-'$ANTLR_VERSION'-complete.jar:$CLASSPATH"\n'\
'java -jar /usr/local/lib/antlr-'$ANTLR_VERSION'-complete.jar "$@"\n'\
> /usr/local/bin/antlr4 && \
    chmod +x /usr/local/bin/antlr4 && \
	ln -s $(which antlr4) /usr/bin/antlr

##################################
####    BUILD THIRD-PARTY    #####
##################################

# Build project deps
RUN cd third-party && make

##################################
####      ENTRYPOINT         #####
##################################

# Start an interactive bash shell
CMD ["/bin/bash"]
# try rebuild
