name: Docker CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker builder instance
        run: docker buildx create --use

      - name: Build system image debian-llvm
        run: |
          docker buildx build --file ./docker/debian-llvm/Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --output=type=docker \
            --tag ${{ secrets.DOCKER_USERNAME }}/debian-llvm:latest \
            --tag debian-llvm:latest \
            ./docker/debian-llvm

      - name: Test system Docker image
        run: docker run --rm debian-llvm:latest /bin/bash -c "echo 'System Docker image built and tested successfully.'"

      - name: Save new Docker cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build project image debian-cedilla
        run: |
          docker buildx build --file ./docker/debian-cedilla/Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --output=type=docker \
            --tag ${{ secrets.DOCKER_USERNAME }}/debian-cedilla:latest \
            --build-arg BASE_IMAGE=debian-llvm:latest \
            ./docker/debian-cedilla

      - name: Test project Docker image
        run: docker run --rm debian-cedilla:latest /bin/bash -c "echo 'Project Docker image built and tested successfully.'"

      - name: Save final Docker cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push Docker images to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/debian-llvm:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/debian-cedilla:latest
