name: Build and Test

on:
  push:
    branches:
      - '*'
    paths:
      - 'path/to/app/Dockerfile'
      - 'path/to/system/Dockerfile'
      - 'path/to/third-party/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'path/to/app/Dockerfile'
      - 'path/to/system/Dockerfile'
      - 'path/to/third-party/**'

jobs:
  check-system-changes:
    runs-on: ubuntu-latest
    outputs:
      system_changed: ${{ steps.check.outputs.system_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug event info
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Before: ${{ github.event.before }}"
          echo "SHA: ${{ github.sha }}"

      - name: Check for changes in system files
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE 'path/to/system/Dockerfile|path/to/third-party/'; then
            echo "::set-output name=system_changed::true"
          else
            echo "::set-output name=system_changed::false"
          fi

      - name: Debug system_changed output
        run: echo "System changed: ${{ steps.check.outputs.system_changed }}"

  build-system-image:
    if: needs.check-system-changes.outputs.system_changed == 'true'
    runs-on: ubuntu-latest
    needs: check-system-changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build and push system image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: path/to/system/Dockerfile
          push: true
          tags: whitehat101/cedc-system:latest
          cache-from: type=registry,ref=whitehat101/cedc-system:cache
          cache-to: type=registry,ref=whitehat101/cedc-system:cache,mode=max

  build-app-image:
    runs-on: ubuntu-latest
    needs: [check-system-changes, build-system-image]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Load Docker cache from Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,ref=whitehat101/cedc:cache,mode=max

      - name: Build and push app image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whitehat101/cedc:latest
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,ref=whitehat101/cedc:cache,mode=max

      - name: Minimize Docker image size
        run: docker image prune -f

      - name: Test Docker image
        run: docker run --rm whitehat101/cedc:latest /bin/bash -c "echo 'Docker image built and tested successfully.'"

      - name: Clean up unused Docker resources
        run: |
          docker system prune -f
          docker builder prune -f
