name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-system-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Check for changes in system.dockerfile or third-party
        id: check_changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD $(git merge-base HEAD origin/main))
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Build and push system image if necessary
        if: env.CHANGED_FILES != '' && env.CHANGED_FILES =~ 'system.dockerfile|third-party'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: system.dockerfile
          tags: whitehat101/cedc-system:latest
          push: true

      - name: Set output for no changes
        if: env.CHANGED_FILES == '' || env.CHANGED_FILES !~ 'system.dockerfile|third-party'
        run: echo "::set-output name=system_image_built::false"

  build-app-image:
    runs-on: ubuntu-latest
    needs: build-system-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Load Docker cache from Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,ref=whitehat101/cedc:cache,mode=max

      - name: Build and push app image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whitehat101/cedc:latest
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,ref=whitehat101/cedc:cache,mode=max

      - name: Minimize Docker image size
        run: docker image prune -f

      - name: Test Docker image
        run: docker run --rm whitehat101/cedc:latest /bin/bash -c "echo 'Docker image built and tested successfully.'"

      - name: Clean up unused Docker resources
        run: |
          docker system prune -f
          docker builder prune -f
