name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check-changes:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2 # Ensure we have enough history for diff

      - name: Fetch all history for diff
        run: git fetch --prune --unshallow

      - name: Check for changes in system-related files
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E '(\.github/workflows/ci.yaml|system.dockerfile|\.system.dockerignore|third-party/)'; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

  system:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changes == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2 # Ensure we have enough history for diff

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Load Docker cache from Docker Hub (System)
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=cedc-system/system:cache
          cache-to: type=registry,ref=cedc-system/system:cache,mode=max

      - name: Build and push base Docker image (System)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: system.dockerfile
          dockerignore: .system.dockerignore
          push: true
          tags: cedc-system/system:latest
          cache-from: type=registry,ref=cedc-system/system:cache
          cache-to: type=registry,ref=cedc-system/system:cache,mode=max

  app:
    runs-on: ubuntu-latest
    needs: [check-changes, system]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2 # Ensure we have enough history for diff

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Load Docker cache from Docker Hub (App)
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,ref=whitehat101/cedc:cache,mode=max

      - name: Build and push Docker image (App)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whitehat101/cedc:latest
          cache-from: type=registry,ref=whitehat101/cedc:cache
          cache-to: type=registry,
